import type { Metadata } from "next";
import Fly from "../components/Flyout";

export const metadata: Metadata = {
  title: "Gaming Place",
  description: "Generated by create next app",
};

export default function ConfiguracaoLayout({
  children
}) {
    return (
      <>
        <Fly/>
        {children}
      </>     
    );
}
